### ISSUE TITLE
Error loading with QuickLisp

### ISSUE THREAD

**Issue by cadr8** [a1b10/cl-xlsx#16]
Getting this error when loading :lisp-xl with quicklisp: Error: #\ů (of type CHARACTER) is not of type BASE-CHAR.

The error is occuring while loading :zip. There seem to be several zip packages, and I'm not clear on which one is being used. I do know it is trying to load this file: quicklisp\dists\quicklisp\software\zip-20150608-git\zip.ofasl.

I'm not super familiar with GitHub, but I'd assume the date code in the pathname would be useful in some way.

Using LispWorks 7.1.2 Pro on Windows 10.

**Comment by gwangjinkim** [comment]
It seems to be aproblem with the zip package of common lisp from which :lisp-xl is dependent.
But this package is :cl-xlsx and not :lisp-xl.

**Comment by cadr8** [comment]
Try adding this in your .lispworks:

 

(set-default-character-element-type 'character)

**Comment by gwangjinkim** [comment]
Since this is about :lisp-xl and not about :cl-xlsx, I close this.
