### ISSUE TITLE
read-xlsx skips empty rows

### ISSUE THREAD

**Issue by slyrus** [a1b10/cl-xlsx#17]
right now empty rows are just skipped. This might be OK in some circumstances, but in others one may want to know that there was an empty row. I propose a keyword arg to read-xlsx such as :keep-empty-rows-as-nil which returns a nil in the list of returned rows where the empty row(s) is(are). I have a patch for this and will make a pull request. Other alternatives are welcome.

**Comment by slyrus** [comment]
I'm reluctant to change the existing behavior of read-xlsx as current code may depend on skipping empty rows.

**Comment by gwangjinkim** [comment]
Thank you for the idea! I think making a keyword with default to skip wouldn't break existing code isn't it?

**Comment by slyrus** [comment]
Yeah, existing code should be fine the way I coded the change in the PR.

**Comment by gwangjinkim** [comment]
Thank you a lot! And sure, backward compatibility is very important. I was
often victim of broken backward compatibility in R packages and was really
annoyed, because there is always a way to sustain backward compatibility
except something was really wrong.
