### ISSUE TITLE
hidden fxml dependencies?

### ISSUE THREAD

**Issue by slyrus** [a1b10/cl-xlsx#19]
If I just load cl-xlsx and then try to call cl-xlsx:read-xlsx I get various fxml errors (undefined navigator, etc...). But if I load both fxml/cxml and fxml/xpath, everything works fine. Should these dependencies be added to the cl-xlsx ASDF dependencies? I'm thinking yes.

**Comment by gwangjinkim** [comment]
Yes it should. I agree!

**Comment by gwangjinkim** [comment]
Added fxml/cxml and fxml/xpath as dependencies.

commit 2c57a6e64c41fed702483b7d24e6634bc2698851 (HEAD -> master, origin/master, origin/HEAD)
Author: gwangjinkim <gwang.jin.kim.phd@gmail.com>
Date:   Thu May 5 20:57:07 2022 +0200

    add :fxml/cxml :fxml/xpath as dependencies
