### ISSUE TITLE
Only every other sheet is read

### ISSUE THREAD

**Issue by slyrus** [a1b10/cl-xlsx#2]
If I have an xlsx file with Sheet1, Sheet2, and Sheet3, only Sheet1 and Sheet3 are read. Similarly, if I have 6 sheets, only sheets 1,3, and 5 are read. Happy to provide a sample xlsx file but it seems easy enough to create one that fails.

**Comment by gwangjinkim** [comment]
Can I have the sample xlsx file?

There will be problems if the content of the sheets is not a simple table.
It is generated only for simplest form of tables.

**Comment by slyrus** [comment]
This one shows the problem:

[six-sheets.xlsx](https://github.com/a1b10/cl-xlsx/files/3811358/six-sheets.xlsx)

**Comment by gwangjinkim** [comment]
Oh you are right. I will try to fix it.

**Comment by gwangjinkim** [comment]
Fixed. Now it should work.

**Comment by gwangjinkim** [comment]
fixed.
